Mark I
Implemented: 9/15/2024

### Features Implemented:

- import of
    - speech recognition - functions to understand user audio input
    - datetime - to get current time, date, etc.
    - requests - to access APIs and links to pages
    - pyttsx3 - to utilize computer’s built in services to output audio
    - webbrowser - not utilized yet
- set voice function
    - changes the voice type using pyttsx3 functions
- set speech rate function
    - changes voice speech using pyttsx3 functions
- speak function
    - speaks the inputed response using pyttsx3 functions
- API key from openweathermap
- Base url of openweathermap to assist when utilizing API
- capture voice input function
    - uses computer microphone to capture audio using speech recognition functions with recognizer
- convert voice to text function
    - converts input audio to text for program to understand using speech recognition functions with recognizer
- get weather function
    - creates URL with base url to openweathermap, utilizes API key to access data and uses input city location to get specific data
    - assigns variables to various statistics provided by openweathermap and prints it out in an easy to understand description of the weather
    - if can’t get data then tells the user
- process voice command function
    - based on detected key words in text, executes certain codes
        - SPARC
            - Introduction
        - Morning Rundown
            - Date & Time using datetime & Weather using get weather function
        - Time
            - datetime to get current time
        - Date
            - datetime to get current date
        - Weather in
            - finds word after in to get city location
            - uses get weather function with city as input to return weather as described in get weather function
        - That’s All
            - Shut off
        - If didn’t understand then tell the user
    - quits function if no key words detected
- main function
    - sets up recognizer
    - sets end_program to false to send loop
    - sets voice to male
    - sets voice speed to 170, slightly faster than average
    - creates a while loop with parameter of end_program
        - variable audio with capture_voice_input to get user audio input
        - variable text with convert_voice_to_text to convert above audio to text with audio as parameter
        - uses text to process voice commands with process_voice_command with text as parameter to run through the keywords and if returns to exit the program then sets end_program to false and quits the loop and ends the program
- if __name__ == “__main__”: main()
    - ensures that the main() function is only executed when the script is run directly, and not when it is imported as a module
    - this is a common pattern used in Python programs to allow code reuse and modularity

### Problems & Solutions:

### Problem 1

```java
 zubinsidhu$ /usr/bin/python3 "/Users/zubinsidhu/Library/CloudStorage/GoogleDrive-zubinsidhu@gmail.com/My Drive/Python/SPARC.py"
/Users/zubinsidhu/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currentlythe 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
/Users/zubinsidhu/Library/Python/3.9/lib/python/site-packages/pyttsx3/drivers/nsss.py:8: ObjCSuperWarning: Objective-C subclass uses super(), but super is not objc.super
  class RunLoopStopper(PyObjCAppHelperRunLoopStopper):
Traceback (most recent call last):
  File "/Users/zubinsidhu/Library/Python/3.9/lib/python/site-packages/pyttsx3/__init__.py", line 20, in init
    eng = _activeEngines[driverName]
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/weakref.py", line 134, in __getitem__
    o = self.data[key]()
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zubinsidhu/Library/CloudStorage/GoogleDrive-zubinsidhu@gmail.com/My Drive/Python/SPARC.py", line 9, in <module>
    engine = pyttsx3.init()
  File "/Users/zubinsidhu/Library/Python/3.9/lib/python/site-packages/pyttsx3/__init__.py", line 22, in init
    eng = Engine(driverName, debug)
  File "/Users/zubinsidhu/Library/Python/3.9/lib/python/site-packages/pyttsx3/engine.py", line 30, in __init__
    self.proxy = driver.DriverProxy(weakref.proxy(self), driverName, debug)
  File "/Users/zubinsidhu/Library/Python/3.9/lib/python/site-packages/pyttsx3/driver.py", line 50, in __init__
    self._module = importlib.import_module(name)
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 850, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/Users/zubinsidhu/Library/Python/3.9/lib/python/site-packages/pyttsx3/drivers/nsss.py", line 26, in <module>
    class NSSpeechDriver(NSObject):
  File "/Users/zubinsidhu/Library/Python/3.9/lib/python/site-packages/pyttsx3/drivers/nsss.py", line 27, in NSSpeechDriver
    @objc.python_method
NameError: name 'objc' is not defined
```

### Tasks & Solution 1

- Figure out why the program won’t even compile and even get the actual run stage
    - Found out that whole following error is coming from engine = pyttsx3.init() because created a separate test file just to utilize this feature and it gave same exact error
- Need to find out why engine cannot be set or why this is happening
    - fixed beginning of error until where it says during handling of above exception by installing pip3 install py3-tts which installed the text to speech function
    - Tested it on sample code which ended up working
    - Fixed problem with engine and pyttsx3

### Problem 2

```java
zubinsidhu$ /usr/bin/python3 "/Users/zubinsidhu/Library/CloudStorage/GoogleDrive-zubinsidhu@gmail.com/My Drive/Python/SPARC.py"
/Users/zubinsidhu/Library/Python/3.9/lib/python/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/zubinsidhu/Library/Python/3.9/lib/python/site-packages/speech_recognition/__init__.py", line 108, in get_pyaudio
    import pyaudio
ModuleNotFoundError: No module named 'pyaudio'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/zubinsidhu/Library/CloudStorage/GoogleDrive-zubinsidhu@gmail.com/My Drive/Python/SPARC.py", line 138, in <module>
    main()
  File "/Users/zubinsidhu/Library/CloudStorage/GoogleDrive-zubinsidhu@gmail.com/My Drive/Python/SPARC.py", line 132, in main
    audio = capture_voice_input()  # Capture voice input
  File "/Users/zubinsidhu/Library/CloudStorage/GoogleDrive-zubinsidhu@gmail.com/My Drive/Python/SPARC.py", line 32, in capture_voice_input
    with sr.Microphone() as source:
  File "/Users/zubinsidhu/Library/Python/3.9/lib/python/site-packages/speech_recognition/__init__.py", line 80, in __init__
    self.pyaudio_module = self.get_pyaudio()
  File "/Users/zubinsidhu/Library/Python/3.9/lib/python/site-packages/speech_recognition/__init__.py", line 110, in get_pyaudio
    raise AttributeError("Could not find PyAudio; check installation")
AttributeError: Could not find PyAudio; check installation
```

### Tasks & Solution 2

- Need to figure out what the second issue is which is separate describing issues importing pyaudio
    - I think I need to install pyaudio again which means I need to use portaudio which is installed with brew but brew is not there so I need to install homebrew but not sure how to do that
    - Successfully installed homebrew by going to main page and following instructions
    - Successfully added brew to path
    - Successfully downloaded portaudio
    - Successfully installed pyaudio with pip3
    - Fixed compiling issue and program is finally running properly → got to stage where program is saying Listening… Yay!

### Tasks & Solution 3

- The entire program works as intended and I am super excited however the voice is really raspy and not very nice so I need to find out how to change the voice and maybe even give it an accent like the movies
    - currently 0 is male which is a raspy terrible voice and 1 is female which sounds heavy russian so we need to change certain settings or import some audio maybe
        - List of voices and their indexes
            
            index-> 0 -- Albert
            index-> 1 -- Alice
            index-> 2 -- Alva
            index-> 3 -- Amélie
            index-> 4 -- Amira
            index-> 5 -- Anna
            index-> 6 -- Bad News
            index-> 7 -- Bahh
            index-> 8 -- Bells
            index-> 9 -- Boing
            index-> 10 -- Bubbles
            index-> 11 -- Carmit
            index-> 12 -- Cellos
            index-> 13 -- Damayanti
            index-> 14 -- Daniel
            index-> 15 -- Daria
            index-> 16 -- Wobble
            index-> 17 -- Eddy (German (Germany))
            index-> 18 -- Eddy (English (UK))
            index-> 19 -- Eddy (English (US))
            index-> 20 -- Eddy (Spanish (Spain))
            index-> 21 -- Eddy (Spanish (Mexico))
            index-> 22 -- Eddy (Finnish (Finland))
            index-> 23 -- Eddy (French (Canada))
            index-> 24 -- Eddy (French (France))
            index-> 25 -- Eddy (Italian (Italy))
            index-> 26 -- Eddy (Portuguese (Brazil))
            index-> 27 -- Ellen
            index-> 28 -- Flo (German (Germany))
            index-> 29 -- Flo (English (UK))
            index-> 30 -- Flo (English (US))
            index-> 31 -- Flo (Spanish (Spain))
            index-> 32 -- Flo (Spanish (Mexico))
            index-> 33 -- Flo (Finnish (Finland))
            index-> 34 -- Flo (French (Canada))
            index-> 35 -- Flo (French (France))
            index-> 36 -- Flo (Italian (Italy))
            index-> 37 -- Flo (Portuguese (Brazil))
            index-> 38 -- Fred
            index-> 39 -- Good News
            index-> 40 -- Grandma (German (Germany))
            index-> 41 -- Grandma (English (UK))
            index-> 42 -- Grandma (English (US))
            index-> 43 -- Grandma (Spanish (Spain))
            index-> 44 -- Grandma (Spanish (Mexico))
            index-> 45 -- Grandma (Finnish (Finland))
            index-> 46 -- Grandma (French (Canada))
            index-> 47 -- Grandma (French (France))
            index-> 48 -- Grandma (Italian (Italy))
            index-> 49 -- Grandma (Portuguese (Brazil))
            index-> 50 -- Grandpa (German (Germany))
            index-> 51 -- Grandpa (English (UK))
            index-> 52 -- Grandpa (English (US))
            index-> 53 -- Grandpa (Spanish (Spain))
            index-> 54 -- Grandpa (Spanish (Mexico))
            index-> 55 -- Grandpa (Finnish (Finland))
            index-> 56 -- Grandpa (French (Canada))
            index-> 57 -- Grandpa (French (France))
            index-> 58 -- Grandpa (Italian (Italy))
            index-> 59 -- Grandpa (Portuguese (Brazil))
            index-> 60 -- Jester
            index-> 61 -- Ioana
            index-> 62 -- Jacques
            index-> 63 -- Joana
            index-> 64 -- Junior
            index-> 65 -- Kanya
            index-> 66 -- Karen
            index-> 67 -- Kathy
            index-> 68 -- Kyoko
            index-> 69 -- Lana
            index-> 70 -- Laura
            index-> 71 -- Lekha
            index-> 72 -- Lesya
            index-> 73 -- Linh
            index-> 74 -- Luciana
            index-> 75 -- Majed
            index-> 76 -- Tünde
            index-> 77 -- Meijia
            index-> 78 -- Melina
            index-> 79 -- Milena
            index-> 80 -- Moira
            index-> 81 -- Mónica
            index-> 82 -- Montse
            index-> 83 -- Nora
            index-> 84 -- Organ
            index-> 85 -- Paulina
            index-> 86 -- Superstar
            index-> 87 -- Ralph
            index-> 88 -- Reed (German (Germany))
            index-> 89 -- Reed (English (UK))
            index-> 90 -- Reed (English (US))
            index-> 91 -- Reed (Spanish (Spain))
            index-> 92 -- Reed (Spanish (Mexico))
            index-> 93 -- Reed (Finnish (Finland))
            index-> 94 -- Reed (French (Canada))
            index-> 95 -- Reed (Italian (Italy))
            index-> 96 -- Reed (Portuguese (Brazil))
            index-> 97 -- Rishi
            index-> 98 -- Rocko (German (Germany))
            index-> 99 -- Rocko (English (UK))
            index-> 100 -- Rocko (English (US))
            index-> 101 -- Rocko (Spanish (Spain))
            index-> 102 -- Rocko (Spanish (Mexico))
            index-> 103 -- Rocko (Finnish (Finland))
            index-> 104 -- Rocko (French (Canada))
            index-> 105 -- Rocko (French (France))
            index-> 106 -- Rocko (Italian (Italy))
            index-> 107 -- Rocko (Portuguese (Brazil))
            index-> 108 -- Samantha
            index-> 109 -- Sandy (German (Germany))
            index-> 110 -- Sandy (English (UK))
            index-> 111 -- Sandy (English (US))
            index-> 112 -- Sandy (Spanish (Spain))
            index-> 113 -- Sandy (Spanish (Mexico))
            index-> 114 -- Sandy (Finnish (Finland))
            index-> 115 -- Sandy (French (Canada))
            index-> 116 -- Sandy (French (France))
            index-> 117 -- Sandy (Italian (Italy))
            index-> 118 -- Sandy (Portuguese (Brazil))
            index-> 119 -- Sara
            index-> 120 -- Satu
            index-> 121 -- Shelley (German (Germany))
            index-> 122 -- Shelley (English (UK))
            index-> 123 -- Shelley (English (US))
            index-> 124 -- Shelley (Spanish (Spain))
            index-> 125 -- Shelley (Spanish (Mexico))
            index-> 126 -- Shelley (Finnish (Finland))
            index-> 127 -- Shelley (French (Canada))
            index-> 128 -- Shelley (French (France))
            index-> 129 -- Shelley (Italian (Italy))
            index-> 130 -- Shelley (Portuguese (Brazil))
            index-> 131 -- Sinji
            index-> 132 -- Tessa
            index-> 133 -- Thomas
            index-> 134 -- Tingting
            index-> 135 -- Trinoids
            index-> 136 -- Whisper
            index-> 137 -- Xander
            index-> 138 -- Yelda
            index-> 139 -- Yuna
            index-> 140 -- Zarvox
            index-> 141 -- Zosia
            index-> 142 -- Zuzana
            
    - pyttsx3 uses the above list of voices and cannot utilize custom voices as it is accessing voices from the computer’s internal systems so we will have to either figure a way to download a voice or choose a different tts system with other voices to incorporate JARVIS or FRIDAY voices